-- =============================================================
-- Migration: 001_create_leads_table.sql
-- Description: Create lead_source enum, lead_status enum,
--              leads table with all constraints, indexes,
--              and auto-update trigger for updated_at.
-- Run order: 1
-- =============================================================

-- -------------------------------------------------------------
-- STEP 1: Create ENUM types
--
-- WHY ENUMS?
--   Enums enforce data integrity at the database level.
--   Even if application code has a bug and sends an invalid
--   value, PostgreSQL will reject it with a clear error.
--   They also make the column self-documenting — any developer
--   reading the schema immediately knows the allowed values.
--   NEVER store these as plain VARCHAR without a CHECK constraint.
-- -------------------------------------------------------------

-- Guard: only create if it doesn't already exist.
-- This makes the migration safe to reason about even if
-- partial runs occurred (though the run.js script handles this).
DO $$ BEGIN
  CREATE TYPE lead_source AS ENUM ('call', 'whatsapp', 'field');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE lead_status AS ENUM ('new', 'interested', 'not_interested', 'converted');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- -------------------------------------------------------------
-- STEP 2: Enable pgcrypto for UUID generation
--
-- WHY UUID PRIMARY KEY?
--   - Sequential integer IDs (1, 2, 3…) expose your data volume
--     to anyone who reads a URL. UUID prevents enumeration attacks.
--   - UUIDs are safe to expose in client-facing URLs/APIs.
--   - gen_random_uuid() is cryptographically random (v4 UUID).
-- -------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -------------------------------------------------------------
-- STEP 3: Create the leads table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (

  -- PRIMARY KEY
  -- UUID v4 generated by PostgreSQL itself.
  -- Generating in the DB (not app) guarantees uniqueness even
  -- if multiple app instances insert simultaneously.
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- LEAD NAME
  -- NOT NULL: a lead without a name is meaningless data.
  -- TRIM via CHECK: prevents "  " (whitespace-only) names.
  -- 100 chars: realistic upper bound for a person's name.
  name VARCHAR(100) NOT NULL
    CONSTRAINT leads_name_not_empty CHECK (TRIM(name) <> ''),

  -- PHONE NUMBER
  -- VARCHAR(20): accommodates international formats like +91-9876543210.
  -- UNIQUE: duplicate phone = duplicate lead. The DB enforces
  --   this even if the application layer has a bug.
  -- NOT NULL: phone is the primary contact method in a CRM.
  phone VARCHAR(20) NOT NULL UNIQUE
    CONSTRAINT leads_phone_not_empty CHECK (TRIM(phone) <> ''),

  -- SOURCE
  -- Uses our custom enum — only 'call', 'whatsapp', 'field' allowed.
  -- NOT NULL: every lead came from somewhere; source is required
  --   for attribution reporting (which channel generates most leads).
  source lead_source NOT NULL,

  -- STATUS
  -- Uses our custom enum.
  -- DEFAULT 'new': every freshly added lead starts as 'new'.
  --   This prevents NULL status bugs in the application.
  -- NOT NULL: status drives the entire CRM workflow.
  status lead_status NOT NULL DEFAULT 'new',

  -- NOTES (optional)
  -- TEXT (no length limit): sales notes can be long.
  -- NULLABLE: not required at lead creation time.
  -- Even though it's not in the assignment spec, this field
  --   costs nothing and prevents a schema migration the moment
  --   a real user asks "can I add notes to a lead?"
  notes TEXT,

  -- TIMESTAMPS
  -- TIMESTAMPTZ (with timezone) is always preferred over
  -- TIMESTAMP. It stores in UTC and converts to the client's
  -- timezone on retrieval — critical for international apps.
  -- NOT NULL + DEFAULT NOW(): auto-populated, never null.
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------------
-- STEP 4: Indexes
--
-- WHY INDEX?
--   Without indexes, PostgreSQL does a full sequential scan —
--   reading every row to find matches. On a table with 10,000
--   leads, a filtered query like WHERE status = 'interested'
--   reads all 10,000 rows. With an index, it reads only the
--   matching rows' storage locations. 10x–100x faster.
--
-- INDEX STRATEGY — only index what you query against:
-- -------------------------------------------------------------

-- Status index: most common filter. "Show me all Interested leads."
CREATE INDEX IF NOT EXISTS idx_leads_status
  ON leads(status);

-- Source index: "Show me all leads from WhatsApp."
CREATE INDEX IF NOT EXISTS idx_leads_source
  ON leads(source);

-- created_at index: default sort order is newest first.
-- DESC index matches the query ORDER BY created_at DESC directly.
CREATE INDEX IF NOT EXISTS idx_leads_created_at
  ON leads(created_at DESC);

-- Composite index for the most common combined query:
-- "Show me all 'interested' leads sorted by newest first."
-- A composite index on (status, created_at) is more efficient
-- than two separate indexes for this pattern.
CREATE INDEX IF NOT EXISTS idx_leads_status_created_at
  ON leads(status, created_at DESC);

-- Text search index for name/phone search feature (bonus feature).
-- GIN index on a tsvector enables full-text search.
-- For simple ILIKE search, a regular index with text_pattern_ops
-- is sufficient and simpler.
CREATE INDEX IF NOT EXISTS idx_leads_name_search
  ON leads(name text_pattern_ops);

CREATE INDEX IF NOT EXISTS idx_leads_phone_search
  ON leads(phone text_pattern_ops);

-- -------------------------------------------------------------
-- STEP 5: Auto-update trigger for updated_at
--
-- WHY A TRIGGER?
--   Without this, updated_at would stay at the creation timestamp
--   forever unless the application explicitly sets it in every
--   UPDATE query. Triggers are the correct tool here — enforce
--   behavior at the database level, not at the application level.
--   This means updated_at is always accurate, regardless of which
--   application, script, or manual query touches the row.
-- -------------------------------------------------------------

-- Create the trigger function (reusable across any table)
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach the trigger to the leads table
DROP TRIGGER IF EXISTS set_leads_updated_at ON leads;

CREATE TRIGGER set_leads_updated_at
  BEFORE UPDATE ON leads
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();

-- -------------------------------------------------------------
-- VERIFICATION QUERIES (run manually to confirm setup)
-- -------------------------------------------------------------
-- Check table columns:
--   \d leads
--
-- Check enum values:
--   SELECT enum_range(NULL::lead_status);
--   SELECT enum_range(NULL::lead_source);
--
-- Check indexes:
--   SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'leads';
--
-- Check trigger:
--   SELECT trigger_name FROM information_schema.triggers WHERE event_object_table = 'leads';
-- -------------------------------------------------------------